packages:
  attrs: pip3 install attrs
  capsul: pip3 install capsul
  cython: pip3 install Cython
  list_imports: pip3 install list-imports
  lmfit: pip3 install lmfit
  matplotlib: pip3 install matplotlib
  nibabel: pip3 install nibabel
  nilearn: pip3 install nilearn
  nipype: pip3 install nipype
  niwidgets: pip3 install niwidgets
  nose: pip3 install nose
  numpy: pip3 install numpy==1.16.6
  pandas: pip3 install pandas
  pyqt5: pip3 install pyqt5
  pytest: pip3 install -U pytest
  ray: pip3 install ray
  scikit-image: pip3 install scikit-image
  scikit-learn: pip3 install -U scikit-learn==0.20.4
  scipy: pip3 install scipy
  sip: pip3 install sip
  sympy: pip3 install sympy
  traits: pip3 install traits==5.2.0
paths:
  data: /tmp/
  histories:
  - /home/domicile-xubuntu/Documents/mri_works_projects/Pipeline_segm_regist/0-1-N4bias_segmentation.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Pipeline_segm_regist/list_structure_separated_from_label_text.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Pipeline_segm_regist/erosion_1px.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Pipeline_segm_regist/full_2.dgr
  - /home/domicile-xubuntu/Desktop/test_submod_list_structures.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Is_Gu/Full_treatment.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Is_Gu/Synchr_Atlas_Image.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/test_mriworks/test_antspy_registration.dgr
  - /home/domicile-xubuntu/Desktop/test_affine_nifti.dgr
  - /home/domicile-xubuntu/Desktop/test_index_array.dgr
  modules: modules
  projects: ../data
version: 20.11.19a
