packages:
  attrs: pip3 install attrs
  capsul: pip3 install capsul
  cython: pip3 install Cython
  list_imports: pip3 install list-imports
  lmfit: pip3 install lmfit
  matplotlib: pip3 install matplotlib
  nibabel: pip3 install nibabel
  nilearn: pip3 install nilearn
  nipype: pip3 install nipype
  niwidgets: pip3 install niwidgets
  nose: pip3 install nose
  numpy: pip3 install numpy==1.16.6
  pandas: pip3 install pandas
  pyqt5: pip3 install pyqt5
  pytest: pip3 install -U pytest
  scikit-image: pip3 install scikit-image
  scikit-learn: pip3 install -U scikit-learn==0.20.4
  scipy: pip3 install scipy
  sip: pip3 install sip
  sympy: pip3 install sympy
  traits: pip3 install traits==5.2.0
paths:
  data: /tmp/
  histories:
  - /home/domicile-xubuntu/Documents/projects_mriworks/test_T2map_flatten_simple.dgr
  - /home/domicile-xubuntu/Documents/projects_mriworks/pb_forloop_save_nifti.dgr
  - /home/domicile-xubuntu/Documents/projects_mriworks/loopfor_recursif_2.dgr
  - /home/domicile-xubuntu/Documents/projects_mriworks/loopfor_recursif.dgr
  - /home/domicile-xubuntu/Apps/python_env/mri_works/NodeEditor/examples/MRIFileManager/PhilipsToNifti.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Isa_Gui/1_N4Bias_Nipype.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Isa_Gui/2_Segmentation_Matlab_PCNN3D.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Isa_Gui/3_register_Atlas.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/ImageJ_profile_TI.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/read_label_Atlas_rat.dgr
  modules: modules
  projects: ../data
version: 20.09.09a
