packages:
  antspy: pip3 install antspyx
  attrs: pip3 install attrs
  capsul: pip3 install capsul
  cython: pip3 install Cython
  h5py: pip3 install h5py
  list_imports: pip3 install list-imports
  lmfit: pip3 install lmfit
  matplotlib: pip3 install matplotlib
  nibabel: pip3 install nibabel
  nilearn: pip3 install nilearn
  nipype: pip3 install nipype
  niwidgets: pip3 install niwidgets
  nose: pip3 install nose
  numpy: pip3 install numpy==1.16.6
  pandas: pip3 install pandas
  pyqt5: pip3 install pyqt5
  pytest: pip3 install pytest
  ray: pip3 install ray
  scikit-image: pip3 install scikit-image
  scikit-learn: pip3 install scikit-learn==0.20.4
  scipy: pip3 install scipy
  sip: pip3 install sip
  sympy: pip3 install sympy
  traits: pip3 install traits==5.2.0
paths:
  data: /tmp/
  diagrams: []
  histories:
  - /home/domicile-xubuntu/Documents/mri_works_projects/Toff/change_resolution_thickness.dgr
  - /home/domicile-xubuntu/Desktop/test_tiff_to_nii.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Toff/test-RegistrationNonLinear_Atlas.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Toff/0-TiffToNifti.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Toff/1-N4bias.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Toff/2-ExtractionBrain.dgr
  - /home/domicile-xubuntu/Desktop/test_splitNifti.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Is_Gu/Full_treatment_multiprocessing.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/Is_Gu/5-Display_Atlas_Images.dgr
  - /home/domicile-xubuntu/Documents/mri_works_projects/testUnit_mri_conv/test_unit_mriconv.dgr
  modules: modules
  projects: ../data
version: 21.02.25a
