packages:
  attrs: pip3 install attrs
  capsul: pip3 install capsul
  cython: pip3 install Cython
  list_imports: pip3 install list-imports
  lmfit: pip3 install lmfit
  matplotlib: pip3 install matplotlib
  nibabel: pip3 install nibabel
  nilearn: pip3 install nilearn
  nipype: pip3 install nipype
  niwidgets: pip3 install niwidgets
  nose: pip3 install nose
  numpy: pip3 install numpy==1.16.6
  pandas: pip3 install pandas
  pyqt5: pip3 install pyqt5
  pytest: pip3 install -U pytest
  scikit-image: pip3 install scikit-image
  scikit-learn: pip3 install -U scikit-learn==0.20.4
  scipy: pip3 install scipy
  sip: pip3 install sip
  sympy: pip3 install sympy
  traits: pip3 install traits==5.2.0
paths:
  data: /tmp/
  histories:
  - /home/omontigon/Documents/mri_works_projects/Matlab_MP3_segmentation_mouse.dgr
  - /home/omontigon/Documents/mri_works_projects/Script_LoopFor_multiprocessing.dgr
  - /home/omontigon/Documents/mri_works_projects/Benchmark_submod_error.dgr
  - /home/omontigon/Documents/mri_works_projects/pb_jsonpath_capsul.dgr
  - /home/omontigon/Documents/mri_works_projects/read_json_irmage.dgr
  - /home/omontigon/Documents/mri_works_projects/free.dgr
  modules: modules
  projects: ../data
version: 20.09.16a
