packages:
  antspy: pip3 install antspyx
  attrs: pip3 install attrs
  capsul: pip3 install capsul
  cython: pip3 install Cython
  h5py: pip3 install h5py
  list_imports: pip3 install list-imports
  lmfit: pip3 install lmfit
  matplotlib: pip3 install matplotlib
  nibabel: pip3 install nibabel
  nilearn: pip3 install nilearn
  nipype: pip3 install nipype
  niwidgets: pip3 install niwidgets
  nose: pip3 install nose
  numpy: pip3 install numpy==1.16.6
  pandas: pip3 install pandas
  pyqt5: pip3 install pyqt5
  pytest: pip3 install pytest
  ray: pip3 install ray
  scikit-image: pip3 install scikit-image
  scikit-learn: pip3 install scikit-learn==0.20.4
  scipy: pip3 install scipy
  sip: pip3 install sip
  sympy: pip3 install sympy
  traits: pip3 install traits==5.2.0
paths:
  data: /tmp/
  histories:
  - /home/omontigon/Bureau/test_xml.dgr
  - /home/omontigon/Documents/mri_works_projects/test_calculs_structure_2.dgr
  - /home/omontigon/Bureau/test_MP_spm_reorient.dgr
  - /home/omontigon/Documents/mri_works_projects/Is_Gu/1-N4bias.dgr
  - /home/omontigon/Documents/mri_works_projects/Is_Gu/3-Registration_Atlas.dgr
  - /home/omontigon/Documents/mri_works_projects/Is_Gu/Full_treatment_multiprocessing.dgr
  - /home/omontigon/Documents/mri_works_projects/Is_Gu/Full_treatment.dgr
  - /home/omontigon/Documents/mri_works_projects/Is_Gu/Full_treatment_one.dgr
  - /home/omontigon/Documents/mri_works_projects/Is_Gu/5-Display_Atlas_Images.dgr
  - /home/omontigon/Bureau/test_bvec_bval.dgr
  modules: modules
  projects: ../data
version: 21.01.12a
